### ISSUE TITLE
Bad URL in VAST_Samples/blob/master/VAST%204.0%20Samples/Inline_Simple.xml

### ISSUE THREAD

**Issue by gmerrall** [InteractiveAdvertisingBureau/VAST_Samples#10]
In this file, and possibly others, there's a link to https://iabtechlab.com/wp-content/uploads/2016/07/VAST-4.0-Short-Intro.mp4. That file is not available on your server due to a permissions issue it seems.
Suggest you resolve the permissions issue or update the URL.

**Comment by dvp236** [comment]
Thanks for reporting. Permission issue is fixed.
