### ISSUE TITLE
Wrong Codec value

### ISSUE THREAD

**Issue by pm-sushant-deshpande** [InteractiveAdvertisingBureau/VAST_Samples#20]
Hi,

What does codec = "0" attribute  signifies in media file of Ad_Verification-test.xml.
As per rfc4281 0 is not valid value. Please let me know how this value should be handled.

**Comment by pm-sushant-deshpande** [comment]
Hi team,

Please help me resolve this issue.
i would  highly appreciate your support and quick response.

Thanks

**Comment by goosemanjack** [comment]
That was a dummy value. The xsd does not verify codec values, so normal surface validations did not catch the issue.
Thank you for pointing this out. We have fixed codec values to be more reasonable in all 4.x samples.
