### ISSUE TITLE
Use RFC2606 example domain names in sample

### ISSUE THREAD

**Issue by noamtamim** [InteractiveAdvertisingBureau/VAST_Samples#5]
Many samples have fake URLs in them, such as `http://url.com`, `http://myErrorURL`, etc.
There are a bunch of real domain names specifically intended for documentation samples:
- example.com
- example.net
- example.org

All samples should use them (unless pointing to real content).

When testing a VAST implementation, and using your samples as test vectors, we may sometimes open those URLs. As a specific example, the VAST 4 [Inline_Simple.xml](https://github.com/InteractiveAdvertisingBureau/VAST_Samples/blob/master/VAST%204.0%20Samples/Inline_Simple.xml) sample contains the following URL for a MediaFile: `http://url.com/content/mid_resolution.mp4`. The problem is that `url.com` is a real site, and this may send false traffic to them (and they might, if malicious, send malicious data to us).

**Comment by dvp236** [comment]
Noted ! Thank you for reporting. This will be fixed soon.

**Comment by dvp236** [comment]
Issue Fixed.
